language: rust
cache: cargo

install: |
  cargo install wasm-pack
  cargo update

script:
- wasm-pack build

deploy:
  edge: true
  provider: script
  script: |
    cd ./pkg/
    npm publish
  on:
    tags: true
    repo: dogamak/ttk91-wasm
