language: rust
cache: cargo

install: |
  cargo install wasm-pack
  cargo update

script:
- wasm-pack build

deploy:
  edge: true
  provider: npm
  email: mitja+npm@karhusaari.me
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: dogamak/ttk91-wasm
